sonar.projectKey=Qualimetrie-team_Smartwarehouse
sonar.organization=smartwarehouse-team
sonar.sources=src,routes
sonar.tests=tests
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info